// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcisatfqbkswofwmugso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjaXNhdGZxYmtzd29md211Z3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwMjgxOTIsImV4cCI6MjA4MzYwNDE5Mn0.k_KeT44-3bd-IwvslB3xjyMfAV2oaG4F62I2tKoIi6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
